added brewfile

diff --git a/client/script/bootstrap b/client/script/bootstrap
--- a/client/script/bootstrap
+++ b/client/script/bootstrap
@@ -3,11 +3,22 @@
 # script/bootstrap: Resolve all dependencies that the application requires to
 #                   run.
 
+# Exit immediately if a command exits with a non-zero status.
 set -e
 
+# Install Homebrew
+/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+
+# Install dependencies from Brewfile
 PATH="$PATH:node_modules/.bin"
 
 cd "$(dirname "$0")/.."
 
+brew bundle check >/dev/null 2>&1  || {
+echo "==> Installing Homebrew dependencies…"
+brew bundle
+}
+
+# Install dependencies from npm
 echo "==> Installing npm dependencies…"
 npm install
